### ISSUE TITLE
Broken in 2016.2 EAP

### ISSUE THREAD

**Issue by JanTvrdik** [juzna/intellij-neon#40]
![image](https://cloud.githubusercontent.com/assets/175109/15762693/831ffc4e-291f-11e6-9c86-af8143199305.png)

**Comment by vysinsky** [comment]
Same here

```
PhpStorm 2016.2 EAP
Build #PS-162.646.18, built on June 2, 2016
PhpStorm EAP User
Expiration date: July 2, 2016
JRE: 1.8.0_76-release-b205 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

It reports `Tab/space mixing`

**Comment by vysinsky** [comment]
Thank you!

**Comment by JanTvrdik** [comment]
Amazing support!

**Comment by Majkl578** [comment]
Hmm, Intellij IDEA doesn't keep compatibility in minor/hotfix versions? Isn't it just something they should revert? :/

**Comment by JanTvrdik** [comment]
This is not a hotfix version, it's new EAP.
